# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Mferri
tagline:          'Un sito fatto con Jekyll e tema lanyon'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Mauro Ferri'
  url:            https://twitter.com/mauroferri

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mauroferri
